# Generated by Django 5.0.7 on 2024-10-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
